# Generated by Django 6.0 on 2026-01-10 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0004_remove_reviewsession_course_remove_week_review_and_more'),
        ('reviews', '0002_delete_reviewticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1550)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('is_seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('review_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tickets', to='reviews.reviewattendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewtickets', to='adminpanel.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('student', 'review_attendance'), name='one_pending_ticket_per_review')],
            },
        ),
    ]
