# Generated by Django 6.0 on 2026-01-10 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviewtickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewticket',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]

