# Generated by Django 6.0 on 2026-01-07 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0004_remove_reviewsession_course_remove_week_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_date', models.DateField()),
                ('review_link', models.CharField(blank=True, max_length=2550, null=True)),
                ('reviewer_name', models.CharField(blank=True, max_length=250, null=True)),
                ('review_name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_sessions', to='adminpanel.course')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tickets', to='adminpanel.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(blank=True, max_length=3550, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('eligible', 'Eligible'), ('not_eligible', 'Not Eligible'), ('pass', 'Pass'), ('fail', 'Fail')], default='eligible', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='adminpanel.studentprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reviews', to='reviews.reviewsession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['eligible', 'not_eligible'])), fields=('student',), name='one_active_upcoming_review_per_student')],
            },
        ),
    ]
