# Generated by Django 6.0 on 2026-01-10 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewTicket',
        ),
    ]
