# Generated by Django 6.0 on 2026-01-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_delete_reviewticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsession',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
