# Generated by Django 6.0 on 2026-02-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_alter_studentprofile_course_alter_user_mobile_number'),
        ('reviews', '0003_reviewsession_is_paid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reviewattendance',
            name='one_active_upcoming_review_per_student',
        ),
        migrations.AlterField(
            model_name='reviewsession',
            name='review_link',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddConstraint(
            model_name='reviewattendance',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['eligible', 'not_eligible'])), fields=('student', 'session'), name='one_active_upcoming_review_per_student'),
        ),
    ]
