# Generated by Django 6.0 on 2026-01-08 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('penalties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='attendance_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.attendancerecord'),
        ),
    ]
