# Generated by Django 6.0 on 2026-01-08 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancerecord_status'),
        ('penalties', '0002_penalty_attendance_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='attendance_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties', to='attendance.attendancerecord'),
        ),
    ]
