# Generated by Django 6.0 on 2026-01-24 06:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalties', '0003_alter_penalty_attendance_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10000.00'))]),
        ),
    ]
