# Generated by Django 6.0 on 2026-03-20 12:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalties', '0004_alter_penalty_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='paid_via',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('online', 'Online')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10000.00'))]),
        ),
    ]
