# Generated by Django 6.0 on 2026-03-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalties', '0005_penalty_paid_via_alter_penalty_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='penalty_type',
            field=models.CharField(choices=[('late', 'Late'), ('absence', 'Absence'), ('misconduct', 'Misconduct'), ('review', 'Review Related'), ('other', 'Other')], max_length=20),
        ),
    ]
