# Generated by Django 6.0 on 2026-03-24 13:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalties', '0007_penalty_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10000.00'))]),
        ),
    ]
