# Generated by Django 6.0 on 2026-02-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_alter_user_email'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workassignment',
            constraint=models.UniqueConstraint(fields=('student', 'work_type'), name='unique_student_work'),
        ),
    ]
