# Generated by Django 6.0 on 2026-01-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_user_reset_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reset_token',
        ),
    ]
