# Generated by Django 6.0 on 2026-01-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_remove_user_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewsession',
            name='course',
        ),
        migrations.RemoveField(
            model_name='week',
            name='review',
        ),
        migrations.RemoveField(
            model_name='week',
            name='course',
        ),
        migrations.RemoveField(
            model_name='week',
            name='student',
        ),
        migrations.DeleteModel(
            name='ReviewAttendance',
        ),
        migrations.DeleteModel(
            name='ReviewSession',
        ),
        migrations.DeleteModel(
            name='Week',
        ),
    ]
