# Generated by Django 6.0 on 2026-03-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
