# Generated by Django 6.0 on 2026-03-20 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_alter_course_description_alter_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Only alphabetic characters are allowed.', regex='^[A-Za-z ]{1,100}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only alphabetic characters are allowed.', regex='^[A-Za-z ]{1,100}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only alphabetic characters are allowed.', regex='^[A-Za-z ]{1,100}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Mobile number must contain only digits and must havee 10 digits', regex='^\\d{10}$')]),
        ),
    ]
